var playerData = [
    ['Player', 'Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Player', 'Player', 'Player', 'Wolf', 'Player', 'Player'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Player', 'Wolf'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Wolf', 'Player', 'Player'],
    ['Player', 'Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Wolf', 'Player', 'Player'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Player', 'Wolf'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player', 'Player'],
];
