// playerData5.js
var playerData = [
    ['Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Player', 'Player', 'Wolf', 'Player', 'Player'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Wolf', 'Player', 'Player'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Wolf', 'Player', 'Player'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Wolf', 'Player', 'Player'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Wolf', 'Player'],
    ['Player', 'Wolf', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Wolf', 'Player', 'Player'],
    ['Wolf', 'Player', 'Player', 'Player', 'Player'],
    ['Player', 'Player', 'Player', 'Player', 'Wolf']
];
