// Content of Questions100.js
const csvData = `Animals,Sports,Jobs,Food,Feelings,Appearance,Comparatives,Activities,Communication,Emotion,Movement
noun,noun,noun,noun,adjective,adjective,adjective,verb,verb,verb,verb
elephant,soccer,plumber,apple,happy,green,slower,cook,talk,love,walk
chicken,tennis,firefighter,orange,sad,beautiful,bigger,swim,tell,hate,run 
dog,basketball,architect,banana,surprised,ugly,stronger,drive,ask,enjoy,sprint
cat,cricket,lawyer,pizza,angry,pretty,shorter,read,answer,wonder,jump
horse,golf,scientist,grapes,bored,tall,longer,study,speak,dislike,skip
zebra,volleyball,nurse,burger,excited,blue,younger,exercise,write,admire,gallop
lion,badminton,engineer,watermelon,confused,purple,older,meditate,communicate,hug,climb
tiger,rugby,doctor,kiwi,amused,orange,yellow,fly,imagine,smile,dance
giraffe,football,accountant,mango,curious,black,grey,build,whisper,cry,swim
monkey,basketball,artist,grape,disgusted,red,pink,fix,shout,laugh,skip
panda,tennis,photographer,pear,content,yellow,green,photograph,nap,question,slide
koala,soccer,chef,blueberry,frustrated,orange,purple,prepare,scream,admire,crawl
kangaroo,volleyball,writer,watermelon,sleepy,pink,short,compose,hum,adore,leap
parrot,golf,pilot,banana,confident,red,blue,diagnose,talk,hug,jump
owl,football,teacher,apple,anxious,purple,yellow,instruct,,smile,run
duck,badminton,scientist,orange,silly,green,white,experiment,,laugh,
penguin,rugby,engineer,strawberry,hopeful,black,red,design,whistle,dance,slide
snake,tennis,nurse,banana,inquisitive,orange,blue,heal,hiss,cry,slither
lizard,basketball,artist,potato,optimistic,green,brown,create,observe,grin,crawl
turtle,golf,firefighter,carrot,cautious,shell,pink,save,whisper,appreciate,walk
frog,badminton,pilot,watermelon,embarrassed,slimy,blue,fly,ribbit,wink,jump
butterfly,rugby,lawyer,kiwi,mischievous,colorful,yellow,defend,flutter,giggle,flutter
dragonfly,football,plumber,mango,relieved,delicate,green,fix,,smirk,soar
bee,badminton,accountant,pineapple,sarcastic,buzzy,black,calculate,buzz,buzz,buzz
bear,tennis,photographer,pear,adventurous,furry,brown,capture,roar,discover,climb
fox,volleyball,writer,blueberry,intrigued,clever,orange,write,,admire,leap
squirrel,basketball,doctor,grapes,perplexed,fluffy,red,diagnose,,observe,
raccoon,tennis,teacher,apple,overwhelmed,masked,brown,instruct,,embrace,slide
deer,golf,scientist,orange,suspicious,graceful,green,experiment,,stare,
hedgehog,badminton,engineer,banana,satisfied,spiky,brown,design,,grin,
`